### ISSUE TITLE
can't decrypt chrome cookies

### ISSUE THREAD

**Issue by DrawTrustDraw** [mis-team/dpapick#2]
Machine is Windows 7 , without domain.
I take C:\users<user>\Appdata\Local\Google\Chrome\User Data\Default\Login Data;
C:\users<user>\appdata\local\google\chrome\user data\Default\Cookies;

Then i use
./chrome --chrome=/home/user/Login_Data --sid=S-1-5-* --credhist=/home/user/CREDHIST --password="PASSWORD" --masterkey=/home/user/folder_with_masterkeys
And all done i got passwords.
But if i use
./chrome --cookie=/home/user/Cookies --sid=S-1-5-* --credhist=/home/user/CREDHIST --password="PASSWORD" --masterkey=/home/user/folder_with_masterkeys
I got this error:
Loading masterkeys...
Trting to decrypt keys...
1
Traceback (most recent call last):
File "./chrome", line 121, in
c.execute("SELECT %s FROM cookies" % ",".join(fields1))
sqlite3.OperationalError: no such column: secure

**Comment by mis-team** [comment]
in new chrome versions sqlite column secure -> is_secure
